=== sid2656/study_webservice/xml/persons.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT persons (person+)>
<!ELEMENT person (sex,name,age,messages+)>
<!ATTLIST person id ID #REQUIRED>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT messages (message+)>
<!ELEMENT message (titile,content)>
<!ELEMENT titile (#PCDATA)>
<!ELEMENT content (#PCDATA)>

=== sid2656/study_webservice/xml/persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persons SYSTEM "D:\sid\workspace_webservice\xml\persons.dtd">
<persons>
	<person id="p2">
		<sex/>
		<name/>
		<age/>
		<messages>
			<message>
				<titile/>
				<content/>
			</message>
		</messages>
	</person>
	<person id="p3">
		<sex></sex>
		<name></name>
		<age></age>
		<messages>
			<message>
				<titile></titile>
				<content></content>
			</message>
		</messages>
	</person>
</persons>
