=== sid2656/study_webservice/02_dtd/src/dtd/classroom.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	1.定义的节点不能重复（cname和sname）
-->
<!ELEMENT classroom (cname,cgrade,sutdents)>
<!ATTLIST classroom cid ID #REQUIRED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT cgrade (#PCDATA)>
<!ELEMENT sutdents (student+)>
<!ELEMENT student (sid,sname,age)>
<!ELEMENT sid (#PCDATA)>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== sid2656/study_webservice/02_dtd/src/dtd/classroom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE classroom SYSTEM "classroom.dtd">
<classroom cid="c1">
	<cname>职专</cname>
	<cgrade>2012</cgrade>
	<sutdents>
		<student>
			<sid></sid>
			<sname></sname>
			<age>12</age>
		</student>
	</sutdents>
</classroom>
